project: ddqn_cartpole
algorithm: DDQN
env_name: CartPole-v1
episodes: 2000
learning_rate: 0.001
gamma: 0.99
epsilon_start: 1.0
epsilon_end: 0.01
epsilon_decay: 0.999
replay_buffer_size: 10000
batch_size: 64
target_update_freq: 4
seed: 36
save_path: models/ddqn_cartpole.pt
log_path: logs/ddqn_cartpole_rewards.csv
test_delay: 10