project: dqn_cartpole
algorithm: DQN
env_name: CartPole-v1
episodes: 2000
learning_rate: 0.001
gamma: 0.99
epsilon_start: 1.0
epsilon_end: 0.01
epsilon_decay: 0.995
replay_buffer_size: 10000
batch_size: 64
target_update_freq: 10
seed: 42
save_path: models/dqn_cartpole.pt
log_path: logs/dqn_cartpole_rewards.csv
